### ISSUE TITLE
Missing columns in _versions table cause error

### ISSUE THREAD

**Issue by drothlis** [technoweenie/acts_as_versioned#1]
acts_as_versioned should determine which columns to version, based on the #{model}_versions table.

The documentation for ActiveRecord::Acts::Versioned::ClassMethods#acts_as_versioned says:

> The _versions table should contain all the fields you want versioned

but this is clearly not the case (with version 0.5.2). For any attributes missing in the _versions table, I get:

> undefined method `attribute=' for #Model::Version:0x180dfe4
> vendor/acts_as_versioned/lib/acts_as_versioned.rb:331:in `send'
> vendor/acts_as_versioned/lib/acts_as_versioned.rb:331:in `clone_versioned_model'
> vendor/acts_as_versioned/lib/acts_as_versioned.rb:330:in `each'
> vendor/acts_as_versioned/lib/acts_as_versioned.rb:330:in `clone_versioned_model'
> vendor/acts_as_versioned/lib/acts_as_versioned.rb:273:in `save_version'

**Comment by technoweenie** [comment]
You can add missing columns to non_versioned_columns, also in the documentation.  Automatic column detection like you've described would be nice if someone has a patch.
