### ISSUE TITLE
Something wonky about the cloned extension

### ISSUE THREAD

**Issue by saizai** [technoweenie/acts_as_versioned#2]
SomeModel.versions.first.some_association.anything doesn't work, even though the association itself is found just fine.

I'm not sure how to fix this; it presumably has something to do with inheritance chaining...

Example 1:

```
>> User.find(Profile.last.versions.last.user_id)
=> #<User id: 1, login: "saizai", ...
>> Profile.last.user
=> #<User id: 1,
>> Profile.last.versions.last.user
NoMethodError: undefined method `user' for #<Profile::Version:0x25fdc30>
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:260:in `method_missing'
```

Example 2:

```
>> Profile.last.versions.last.updater
=> #<User id: 1, login: "saizai", ...
>> Profile.last.versions.last.updater.name
NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.include?
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:142:in `create_time_zone_conversion_attribute?'
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:75:in `define_attribute_methods'
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:71:in `each'
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:71:in `define_attribute_methods'
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:351:in `respond_to?'
from /Users/saizai/Dropbox/workspace/hyperdictionary/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:213:in `method_missing'
from (irb):99
from :0
>> User.find(Profile.last.versions.last.updater_id)
=> #<User id: 1, login: "saizai", ...
>> User.find(Profile.last.versions.last.updater_id).name
=> "Rootage"
>> Profile.last.versions.last
=> #<Profile::Version id: 2, ...
>> Profile.last.versions.last.skip_time_zone_conversion_for_attributes
=> []
>> Profile.last.versions.last.updater.skip_time_zone_conversion_for_attributes
=> nil
>> User.find(Profile.last.versions.last.updater_id).skip_time_zone_conversion_for_attributes
=> []
```

**Comment by saizai** [comment]
Turns out this is due to a Rails bug: http://rails.lighthouseapp.com/projects/8994/tickets/1339-arbase-should-not-be-nuking-its-children-just-because-it-lost-interest

The patch on that link fixes this issue but is not deployed to Rails.
